version: "2"
services:
  indico-web: &indico-web
    build: indico
    command: /opt/indico/run_indico.sh
    depends_on:
      - indico-redis
      - indico-celery
    ports:
      - "8000:8000"
    links:
      - indico-redis
    environment:
      - BASEURL=http://localhost:8080
      - PGHOST=indico-postgres # Adapt in case of using external DB
      - PGUSER=indico # Adapt in case of using external DB
      - PGPASSWORD=indicopass # Adapt in case of using external DB
      - PGDATABASE=indico # Adapt in case of using external DB
      - PGPORT=5432 # Adapt in case of using external DB
      - SMTP_SERVER=localhost
      - SMTP_PORT=8025
      - SMTP_LOGIN
      - SMTP_PASSWORD
      - SMTP_USE_TLS=no
      - INDICO_DEFAULT_TIMEZONE
      - INDICO_DEFAULT_LOCALE
      - INDICO_ROUTE_OLD_URLS=False
      - INDICO_CHECKIN_APP_CLIENT_ID
      - INDICO_CUSTOMIZATION_DIR=/opt/indico/custom
      - INDICO_CUSTOMIZATION_DEBUG=False
      - INDICO_LOGO_URL
      - REDIS_CACHE_URL=redis://indico-redis:6379/1
      - CELERY_BROKER=redis://indico-redis:6379/0
    volumes:
      - './data/archive:/opt/indico/archive:z'
      - './data/log/nginx:/opt/indico/log/nginx:z'
      - 'static-files:/opt/indico/static:z'
      - 'customization:/opt/indico/custom:z'
    tmpfs:
        - /opt/indico/tmp:rw,size=787448k,uid=1000
  indico-celery:
    <<: *indico-web
    command: /opt/indico/run_celery.sh
    depends_on:
      - indico-redis
    ports: []
    volumes: []
  indico-redis:
    image: redis
  indico-postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=indico
        - POSTGRES_PASSWORD=indicopass
        - POSTGRES_DB=indico
  indico-nginx:
    image: nginx
    ports:
      - "8080:8080"
    command: bash -c "usermod -G users nginx && nginx -g 'daemon off;'"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/indico.conf'
    volumes_from:
      - indico-web
volumes:
  static-files:
  customization:
